from typing import List, Tuple

magic_db: List[Tuple[str, List[str], int, List[str]]] = [
    (
        "island",  # Name
        ["land"],  # Card Type
        1993,  # year
        "none",  # Flavor text
        ["colorless"], # Color
    ),
    (
        "mountain",
        ["land"],
        1993,
        "none",
        ["colorless"],
    ),
    (
        "swamp",
        ["land"],
        1993,
        "none",
        ["colorless"],
    ),
    (
        "plains",
        ["land"],
        1993,
        "none",
        ["colorless"],
    ),
    (
        "forest",
        ["land"],
        1993,
        "none",
        ["colorless"],
    ),
    (
        "black lotus",
        ["artifact"],
        1993,
        "none",
        ["colorless"],
    ),
    (
        "smothering Tithe",
        ["enchantment"],
        2019,
        "i await your donation",
        ["white"],
    ),
    (
        "rhystic study",
        ["enchantment"],
        2000,
        "friends teach what you want to know. Enemies teach what you need to know.",
        ["blue"],
    ),
    (
        "chatterfang, Squirrel General",
        ["creature"],
        2019,
        "none",
        ["green"],
    ),
    (
        "sliver overlord",
        ["creature"],
        2003,
        "the end of evolution",
        ["white", "red", "green", "blue", "black"],
    ),
    (
        "the one ring",
        ["artifact"],
        2023,
        "none",
        ["colorless"],
    ),
    (
        "three visits",
        ["sorcery"],
        1999,
        "trying to meet a worthy man in the wrong way is as bad as closing the door on an invited guest.",
        ["green"],
    ),
    (
        "high tide",
        ["instant"],
        1994,
        "by the time their enemies noticed the sea's changing mood, the Vodalians had often shifted formation and were ready to attack.",
        ["blue"],
    ),
    (
        "mystic remora",
        ["enchantment"],
        1995,
        "none",
        ["blue"],
    ),
    (
        "kaalia of the vast",
        ["creature"],
        2011,
        "i'll have my revenge if I have to call on every force from above and below.",
        ["red", "white", "black"],
    ),
    (
        "tivit, seller of secrets",
        ["creature"],
        2022,
        "none",
        ["blue", "white", "black"],
    ),
    (
        "fblthp, the lost",
        ["creature"],
        2019,
        "none",
        ["blue"],
    ),
    (
        "mana drain",
        ["instant"],
        1994,
        "none",
        ["blue"],
    ),
    (
        "world fire",
        ["sorcery"],
        2013,
        "even the smallest spark may set a world ablaze.",
        ["red"],
    ),
    (
        "cyberman conversion",
        ["instant"],
        2023,
        "do not fear. we will take your fear from you. you will be like us.",
        ["blue"],
    ),
    (
        "solemn simulacrum",
        ["artifact", "creature"],
        2003,
        "none",
        ["colorless"],
    ),
    (
        "urza's saga",
        ["enchantment", "land"],
        2021,
        "none",
        ["colorless"],
    ),
    (
        "nekusar, the mindrazer",
        ["creature"],
        2013,
        "his enemies wondered if the lich king's brutal death and unnatural rebirth had been his plan all along.",
        ["blue", "black", "red"],
    ),
    (
        "belbe, corrputed overseer",
        ["creature"],
        2020,
        "those who wish to become evincar must first cast off the shackles of compassion.",
        ["green", "black"],
    ),
    (
        "asmoranomardicadaistinaculdacar",
        ["creature"],
        2021,
        "none",
        ["red", "black"],
    ),
    (
        "solitude",
        ["creature"],
        2021,
        "none",
        ["white"],
    ),
    (
        "the first sliver",
        ["creature"],
        2019,
        "none",
        ["white", "blue", "red","black", "green"],
    ),
]
